development:
  dialect: postgres
  database: cc_development
  user: postgres
  password: asusmhdsh
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:asusmhdsh@127.0.0.1:5432/cc_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:asusmhdsh@127.0.0.1:5432/cc_production?sslmode=disable"}}
