// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type NewBot struct {
	IP          string `json:"ip"`
	WhoAmI      string `json:"whoAmI"`
	Os          string `json:"os"`
	InstallDate string `json:"installDate"`
	Admin       bool   `json:"admin"`
	Av          string `json:"av"`
	CPU         string `json:"cpu"`
	Gpu         string `json:"gpu"`
	Version     string `json:"version"`
}
